### ISSUE TITLE
Proyecto Visual Studio UX UI

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-j-a-k#1]
[REPORTE VISUAL STUDIO UX UI.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-j-a-k/files/14312825/REPORTE.VISUAL.STUDIO.UX.UI.pdf)

Integrantes:
Ana Kimberly Hernández Pérez
Ameli Reyes Hernández
Jaczibeth Cruz Ramírez

**Comment by Ariadnamonserrat10** [comment]
99/100
solo por que en la portada menciona que es la practica 2 aun pero de ahi en fuera todo cumple con lo establecido.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
